server:
  port: ${SERVER_PORT:8081}
  shutdown: graceful

spring:
  application:
    name: user-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/user_db}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  lifecycle:
    timeout-per-shutdown-phase: 20s
  sql:
    init:
      mode: always # 1. Bắt buộc chạy script kể cả khi dùng MySQL/Postgres

# JWT Config (Tự định nghĩa)
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: ${JWT_EXPIRATION:86400000}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true # Ưu tiên dùng IP thay vì Hostname trong Docker
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

# Core Security config (override từ core-security module)
core-security:
  public-paths:
    - /api/v1/auth/**
    - /actuator/**

