server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: order-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/order_db}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update

axon:
  axonserver:
    servers: ${AXON_AXONSERVER_SERVERS:localhost:8124}
  serializer:
    general: jackson
    events: jackson
    messages: jackson

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true # Ưu tiên dùng IP thay vì Hostname trong Docker