server:
  port: ${SERVER_PORT:8082}
  shutdown: graceful

spring:
  application:
    name: product-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/product_db}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  lifecycle:
    timeout-per-shutdown-phase: 20s
  sql:
    init:
      mode: always

axon:
  axonserver:
    servers: ${AXON_AXONSERVER_SERVERS:localhost:8124}
    context: default
    connect-timeout: 15000
    reconnect-interval: 3000
  serializer:
    general: jackson
    events: jackson
    messages: jackson

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

# ─── gRPC Server ───
grpc:
  server:
    port: ${GRPC_SERVER_PORT:9090}

